import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  classifyConflictPath,
  unionLines,
  pickNewerByTimestamp,
  jsonCarriesTimestamp,
  classifyBranchIntegration,
} from '../scripts/consolidation-resolve.js';

// ── signal-driven classification ──

test('lockfiles across ecosystems → regenerate (basename signal, path-agnostic)', () => {
  for (const p of [
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'Cargo.lock', 'poetry.lock',
    'go.sum', 'Gemfile.lock', 'composer.lock', '.terraform.lock.hcl', 'a/b/c/yarn.lock',
  ]) {
    const r = classifyConflictPath(p);
    assert.equal(r.policy, 'regenerate', `${p} should regenerate`);
    assert.equal(r.class, 'lockfile');
  }
});

test('generated artifacts → regenerate via @generated HEADER signal (any path)', () => {
  for (const head of [
    '// @generated by protoc', '/* eslint-disable */\n// Code generated by GraphQL Codegen. DO NOT EDIT.',
    '# GENERATED — do not edit', '// autogenerated', '// @generated\nexport const x = 1;',
  ]) {
    const r = classifyConflictPath('any/path/whatever.ts', { headText: head });
    assert.equal(r.policy, 'regenerate', `header "${head.slice(0, 24)}…" should regenerate`);
  }
});

test('generated artifacts → regenerate via configured glob (header-less)', () => {
  const r = classifyConflictPath('assets/aideck-consumer/schema.json', { generatedGlobs: ['assets/aideck-consumer/schema.json'] });
  assert.equal(r.policy, 'regenerate');
});

test('union via the merge=union ATTRIBUTE git already honors (no path list)', () => {
  // ANY path the orchestrator reports as merge=union — no hardcoded ledger paths.
  for (const p of ['reviews/INDEX.md', 'CHANGELOG.md', 'docs/audit-log.ndjson', 'whatever/log.md']) {
    assert.equal(classifyConflictPath(p, { mergeUnion: true }).policy, 'union', `${p} with merge=union → union`);
  }
  // without the attribute, the same path is NOT auto-unioned (fail-closed)
  assert.equal(classifyConflictPath('CHANGELOG.md').policy, 'eject');
});

test('git-ignored runtime artifact → take-delete (gitIgnored signal, any path)', () => {
  assert.equal(classifyConflictPath('config/.runtime-cache.json', { gitIgnored: true }).policy, 'take-delete');
  assert.equal(classifyConflictPath('.app/state.json', { gitIgnored: true }).policy, 'take-delete');
});

test('runtime artifact via repo-config glob → take-delete (gitignore signal unreliable mid-merge)', () => {
  assert.equal(classifyConflictPath('.atomic-skills/focus.json', { runtimeGlobs: ['.atomic-skills/focus.json'] }).policy, 'take-delete');
});

test('.gitignore / .gitattributes → union by GENERIC name-set (present in every repo)', () => {
  assert.equal(classifyConflictPath('.gitignore').policy, 'union');
  assert.equal(classifyConflictPath('.gitattributes').policy, 'union');
  assert.equal(classifyConflictPath('.gitignore').class, 'config-union');
});

test('pointwise JSON snapshot → last-writer-wins (jsonTimestamped signal)', () => {
  assert.equal(classifyConflictPath('any/state.json', { jsonTimestamped: true }).policy, 'last-writer-wins');
});

test('narrative index → take-ours-verify ONLY via repo config (fuzzy, never silent)', () => {
  const r = classifyConflictPath('.atomic-skills/projects/x/PROJECT-STATUS.md', { narrativeGlobs: ['**/PROJECT-STATUS.md'] });
  assert.equal(r.policy, 'take-ours-verify');
  // not configured → ejects, not silently taken
  assert.equal(classifyConflictPath('docs/STATUS.md').policy, 'eject');
});

test('FAIL-CLOSED: no signal → eject (semantic sources, and unknown files)', () => {
  for (const p of ['scripts/emit-focus.js', 'skills/core/project.md', 'package.json', 'src/app.ts', 'README.md']) {
    const r = classifyConflictPath(p);
    assert.equal(r.policy, 'eject', `${p} must eject with no signal`);
    assert.equal(r.auto, false);
  }
});

test('never-throws on garbage path/ctx → ejects', () => {
  for (const bad of [null, undefined, 42, {}, []]) {
    assert.equal(classifyConflictPath(bad).policy, 'eject');
  }
  assert.equal(classifyConflictPath('x', null).policy, 'eject');
});

// ── GENERALITY (non-circular): OOD files the classifier was NEVER tuned to ──
// These are the exact 13 out-of-distribution paths that the path-keyed version
// EJECTED (zero generalization). With signals supplied, they now auto-resolve —
// proving the classifier carries signal, not memorized atomic-skills paths.
test('OOD GENERALITY: foreign-repo equivalents auto-resolve by signal, not by path', () => {
  const cases = [
    // lockfiles (basename signal)
    ['yarn.lock', {}, 'regenerate'],
    ['Cargo.lock', {}, 'regenerate'],
    ['go.sum', {}, 'regenerate'],
    ['Gemfile.lock', {}, 'regenerate'],
    // generated (header signal) — a Rust/proto/graphql repo's codegen
    ['src/__generated__/schema.ts', { headText: '/* @generated */' }, 'regenerate'],
    ['api/types.ts', { headText: '// Code generated by openapi-generator. DO NOT EDIT.' }, 'regenerate'],
    ['lib/proto/service_pb.js', { headText: '// source: service.proto\n// @generated' }, 'regenerate'],
    // append ledger (merge=union attribute the foreign repo configured)
    ['CHANGELOG.md', { mergeUnion: true }, 'union'],
    ['docs/audit-log.ndjson', { mergeUnion: true }, 'union'],
    // runtime (gitignored)
    ['.terraform.lock.hcl', {}, 'regenerate'], // also a lockfile name → regenerate
    ['config/.runtime-cache.json', { gitIgnored: true }, 'take-delete'],
  ];
  for (const [p, ctx, expected] of cases) {
    const r = classifyConflictPath(p, ctx);
    assert.equal(r.policy, expected, `OOD ${p} → expected ${expected}, got ${r.policy} (${r.class})`);
    assert.equal(r.auto, true, `OOD ${p} should auto-resolve`);
  }
});

// ── pure helpers (generic) ──

test('unionLines: ours order preserved + theirs-only appended, deduped', () => {
  assert.equal(unionLines('a\nb\nc\n', 'b\nd\ne\n'), 'a\nb\nc\nd\ne\n');
  assert.equal(unionLines('x\ny', ''), 'x\ny');
});

test('pickNewerByTimestamp + jsonCarriesTimestamp: newer wins; fail-closed null when undecidable', () => {
  const older = JSON.stringify({ lastUpdated: '2026-06-17T23:00:00Z' });
  const newer = JSON.stringify({ lastUpdated: '2026-06-19T19:53:00Z' });
  assert.equal(pickNewerByTimestamp(older, newer).side, 'theirs');
  assert.equal(jsonCarriesTimestamp(older, newer), true);
  assert.equal(pickNewerByTimestamp('{bad', '{}'), null);
  assert.equal(jsonCarriesTimestamp(JSON.stringify({ a: 1 }), JSON.stringify({ b: 2 })), false);
});

test('classifyBranchIntegration: ahead>0 merge; ahead=0+revert → revert-of-revert; ahead=0 → skip', () => {
  assert.equal(classifyBranchIntegration({ aheadCount: 5 }).action, 'merge');
  assert.equal(classifyBranchIntegration({ aheadCount: 0, revertOfMergeSha: 'abc' }).action, 'revert-of-revert');
  assert.equal(classifyBranchIntegration({ aheadCount: 0 }).action, 'skip-noop');
  assert.equal(classifyBranchIntegration(null).action, 'merge');
});
